//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterbotixMoveitInterface
{
    [Serializable]
    public class MoveItPlanResponse : Message
    {
        public const string k_RosMessageName = "interbotix_moveit_interface/MoveItPlan";
        public override string RosMessageName => k_RosMessageName;

        //  message if the planning or execution was successful; this is displayed in the custom GUI.
        public Std.StringMsg msg;
        //  boolean to easily check if the planning or execution was successful.
        public bool success;

        public MoveItPlanResponse()
        {
            this.msg = new Std.StringMsg();
            this.success = false;
        }

        public MoveItPlanResponse(Std.StringMsg msg, bool success)
        {
            this.msg = msg;
            this.success = success;
        }

        public static MoveItPlanResponse Deserialize(MessageDeserializer deserializer) => new MoveItPlanResponse(deserializer);

        private MoveItPlanResponse(MessageDeserializer deserializer)
        {
            this.msg = Std.StringMsg.Deserialize(deserializer);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.msg);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "MoveItPlanResponse: " +
            "\nmsg: " + msg.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
