//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterbotixHandJoy
{
    [Serializable]
    public class GripperPositionResponse : Message
    {
        public const string k_RosMessageName = "interbotix_hand_joy/GripperPosition";
        public override string RosMessageName => k_RosMessageName;

        //  returns 1 if opening the gripper, 2 if closing and 0 if failure
        public sbyte mode_of_operation;

        public GripperPositionResponse()
        {
            this.mode_of_operation = 0;
        }

        public GripperPositionResponse(sbyte mode_of_operation)
        {
            this.mode_of_operation = mode_of_operation;
        }

        public static GripperPositionResponse Deserialize(MessageDeserializer deserializer) => new GripperPositionResponse(deserializer);

        private GripperPositionResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode_of_operation);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode_of_operation);
        }

        public override string ToString()
        {
            return "GripperPositionResponse: " +
            "\nmode_of_operation: " + mode_of_operation.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
