//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterbotixHandJoy
{
    [Serializable]
    public class SetWaistAngleRequest : Message
    {
        public const string k_RosMessageName = "interbotix_hand_joy/SetWaistAngle";
        public override string RosMessageName => k_RosMessageName;

        //  requested joint angle command
        public float waist_angle;

        public SetWaistAngleRequest()
        {
            this.waist_angle = 0.0f;
        }

        public SetWaistAngleRequest(float waist_angle)
        {
            this.waist_angle = waist_angle;
        }

        public static SetWaistAngleRequest Deserialize(MessageDeserializer deserializer) => new SetWaistAngleRequest(deserializer);

        private SetWaistAngleRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.waist_angle);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.waist_angle);
        }

        public override string ToString()
        {
            return "SetWaistAngleRequest: " +
            "\nwaist_angle: " + waist_angle.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
