//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterbotixHandJoy
{
    [Serializable]
    public class SetWaistAngleResponse : Message
    {
        public const string k_RosMessageName = "interbotix_hand_joy/SetWaistAngle";
        public override string RosMessageName => k_RosMessageName;

        //  returns true if successful, false if not
        public bool success;

        public SetWaistAngleResponse()
        {
            this.success = false;
        }

        public SetWaistAngleResponse(bool success)
        {
            this.success = success;
        }

        public static SetWaistAngleResponse Deserialize(MessageDeserializer deserializer) => new SetWaistAngleResponse(deserializer);

        private SetWaistAngleResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "SetWaistAngleResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
